# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: 'Test'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
      maxParallel: 2

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
          displayName: Add conda to PATH
      - bash: conda create --yes --quiet --name testenv
          displayName: Create Anaconda environment
      - bash: |
            source activate myEnvironment
            conda install --yes --quiet --name testenv pybind11
          displayName: Install Anaconda packages

          #      - script: |
          #python -m pip install flake8
          #flake8 .
          #displayName: 'Run lint tests'|
      - script: |
          wget https://github.com/pybind/pybind11/archive/v2.2.4.tar.gz

        displayName: Install pybind11
      - script: python setup.py install
        displayName: Install using setup.py
